-- +goose Up
CREATE TYPE owner_kind       AS ENUM ('world', 'player', 'chat');
CREATE TYPE ledger_kind      AS ENUM ('money', 'experience');
CREATE TYPE operation_source AS ENUM ('telegram');

CREATE TABLE owner (
    id          bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind        owner_kind  NOT NULL,
    telegram_id bigint,                                          -- player / chat only
    created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX owner_kind_telegram_id_key ON owner (kind, telegram_id) WHERE telegram_id IS NOT NULL;
CREATE UNIQUE INDEX owner_single_world_key     ON owner ((true))            WHERE kind = 'world';

CREATE TABLE scope_definition (
    id         smallint   PRIMARY KEY,
    code       text       NOT NULL UNIQUE,
    owner_kind owner_kind NOT NULL
);
CREATE TABLE account_definition (
    id                  smallint    PRIMARY KEY,
    scope_definition_id smallint    NOT NULL REFERENCES scope_definition (id),
    code                text        NOT NULL,
    kind                ledger_kind NOT NULL,
    controlled          boolean     NOT NULL,
    CONSTRAINT account_definition_scope_code_key UNIQUE (scope_definition_id, code)   -- covers the FK
);

CREATE TABLE scope (
    id                  bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id            bigint      NOT NULL REFERENCES owner (id),
    scope_definition_id smallint    NOT NULL REFERENCES scope_definition (id),
    created_at          timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT scope_singleton_key UNIQUE (owner_id, scope_definition_id)   -- singleton + covers owner FK
);
CREATE INDEX scope_definition_idx ON scope (scope_definition_id);          -- covers definition FK

CREATE TABLE account (
    id                    bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_id              bigint      NOT NULL REFERENCES scope (id),
    account_definition_id smallint    NOT NULL REFERENCES account_definition (id),
    created_at            timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT account_scope_definition_key UNIQUE (scope_id, account_definition_id)   -- one per scope + covers scope FK
);
CREATE INDEX account_definition_idx ON account (account_definition_id);               -- covers definition FK

CREATE TABLE account_balance (
    account_id bigint        PRIMARY KEY REFERENCES account (id),
    balance    numeric(30,5) NOT NULL DEFAULT 0,
    CONSTRAINT account_balance_nonnegative CHECK (balance >= 0)
);

CREATE TABLE player_operation (
    id           bigint           GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    source       operation_source NOT NULL,
    operation_id text             NOT NULL,
    created_at   timestamptz      NOT NULL DEFAULT now(),
    CONSTRAINT player_operation_source_operation_id_key UNIQUE (source, operation_id)
);
CREATE TABLE manual_correction (
    id         bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    actor      text        NOT NULL,
    reason     text        NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE journal_entry (
    id                   bigint      GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ts                   timestamptz NOT NULL DEFAULT now(),
    player_operation_id  bigint      REFERENCES player_operation (id),
    manual_correction_id bigint      REFERENCES manual_correction (id),
    CONSTRAINT journal_entry_exactly_one_basis CHECK (num_nonnulls(player_operation_id, manual_correction_id) = 1)
);
CREATE UNIQUE INDEX journal_entry_player_operation_key  ON journal_entry (player_operation_id)  WHERE player_operation_id  IS NOT NULL;
CREATE UNIQUE INDEX journal_entry_manual_correction_key ON journal_entry (manual_correction_id) WHERE manual_correction_id IS NOT NULL;
CREATE INDEX journal_entry_ts_idx ON journal_entry (ts);

CREATE TABLE posting (
    id               bigint        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    journal_entry_id bigint        NOT NULL REFERENCES journal_entry (id),
    account_id       bigint        NOT NULL REFERENCES account (id),
    amount           numeric(30,5) NOT NULL,
    CONSTRAINT posting_amount_nonzero CHECK (amount <> 0)
);
CREATE INDEX posting_journal_entry_idx ON posting (journal_entry_id);
CREATE INDEX posting_account_idx       ON posting (account_id);

INSERT INTO scope_definition (id, code, owner_kind) VALUES (1, 'world', 'world'), (2, 'attributes', 'player');
INSERT INTO account_definition (id, scope_definition_id, code, kind, controlled) VALUES
    (1, 1, 'money', 'money', false), (2, 1, 'experience', 'experience', false),
    (3, 2, 'money', 'money', true),  (4, 2, 'experience', 'experience', true);
INSERT INTO owner   (id, kind)                            VALUES (1, 'world');
INSERT INTO scope   (id, owner_id, scope_definition_id)   VALUES (1, 1, 1);
INSERT INTO account (id, scope_id, account_definition_id) VALUES (1, 1, 1), (2, 1, 2);
SELECT setval(pg_get_serial_sequence('owner',   'id'), 1, true);
SELECT setval(pg_get_serial_sequence('scope',   'id'), 1, true);
SELECT setval(pg_get_serial_sequence('account', 'id'), 2, true);
